apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gateway
      name: gateway
    spec:
      ports:
        - name: "80"
          port: 80
          targetPort: 80
      selector:
        io.kompose.service: gateway
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: reservation
      name: reservation
    spec:
      ports:
        - name: "80"
          port: 80
          targetPort: 80
      selector:
        io.kompose.service: reservation
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: payment
      name: payment
    spec:
      ports:
        - name: "80"
          port: 80
          targetPort: 80
      selector:
        io.kompose.service: payment
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
      name: postgres
    spec:
      ports:
        - name: "5432"
          port: 5432
          targetPort: 5432
      selector:
        io.kompose.service: postgres
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: loyalty
      name: loyalty
    spec:
      ports:
        - name: "80"
          port: 80
          targetPort: 80
      selector:
        io.kompose.service: loyalty
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gateway
      name: gateway
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: gateway
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            io.kompose.service: gateway
        spec:
          containers:
            - env:
                - name: PORT
                  value: "8080"
              image: nikitarubcov99/gateway
              name: gateway
              ports:
                - containerPort: 80
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: reservation
      name: reservation
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: reservation
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            io.kompose.service: reservation
        spec:
          containers:
            - env:
                - name: PORT
                  value: "8070"
              image: nikitarubcov99/reservation
              name: loyalty
              ports:
                - containerPort: 80
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: payment
      name: payment
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: payment
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            io.kompose.service: payment
        spec:
          containers:
            - env:
                - name: PORT
                  value: "8060"
              image: nikitarubcov99/payment
              name: payment
              ports:
                - containerPort: 80
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
      name: postgres
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: postgres
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            io.kompose.service: postgres
        spec:
          containers:
            - env:
                - name: POSTGRES_DB
                  value: postgres
                - name: POSTGRES_PASSWORD
                  value: postgres
                - name: POSTGRES_USER
                  value: postgres
              image: library/postgres:13
              name: postgres
              ports:
                - containerPort: 5432
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: loyalty
      name: loyalty
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: loyalty
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            io.kompose.service: loyalty
        spec:
          containers:
            - env:
                - name: PORT
                  value: "8050"
              image: nikitarubcov99/loyalty
              name: loyalty
              ports:
                - containerPort: 80
              resources: {}
          restartPolicy: Always
    status: {}
kind: List
metadata: {}